<?php

namespace Amicale\AccueilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
    /**
     * retourne tous les commercants qui ne sont pas encore liés à l'évenement passé en parametres
     * @author CMO
     * @param \Amicale\AccueilBundle\Entity\Evenement $evenement
     * @return Doctrine Collection de Commercant
     */
    public function getCommercantsRestantsAChoisir(\Amicale\AccueilBundle\Entity\Evenement $evenement){
        $query = $this->_em->createQuery('SELECT c FROM AmicaleAccueilBundle:Commercant c WHERE c.id not in ('.$evenement->getChaineIdCommercants().')');
        return $query->getResult();
    }
}
