<?php

namespace Amicale\AccueilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatutCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutCommandeRepository extends EntityRepository
{
    
}
