<?php

namespace Amicale\AccueilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeProduitRepository extends EntityRepository
{
    public function findAll($array_criteria = null, $array_sort = null) {
        return $this->findBy(array(), array('nom' => 'asc'));
    }
}
