parameters:
#    amicale_accueil.example.class: Amicale\AccueilBundle\Example
    factory_commande.class: Amicale\AccueilBundle\Factory\CommandeFactory

services:
    amicale_new_commande:
        class: "%factory_commande.class%"
        arguments: [ @doctrine.orm.entity_manager, @security.context ]